const cursos = [

    {id: 1,
    imagen: "img/assault.jpg",
    titulo: 'Mejora tu Rendimiento en Assault Bike',
    profesor:'Matias Cambareri',
    calificacion: "img/5estrellas.png",
    precio: 2200,
    descuento:1500},

    {id: 2,
    imagen: "img/backsquat.jpg",
    titulo: 'Sube tu RM de Back Squat',
    profesor:'Matias Cambareri',
    calificacion: "img/4estrellas.png",
    precio: 3000,
    descuento:2400},

    {id: 3,
    imagen: "img/barmuscleup.jpg",
    titulo: 'Logra tu Primer Bar Muscle Up',
    profesor:'Matias Cambareri',
    calificacion: "img/45estrellas.png",
    precio: 2300,
    descuento:1800},

    {id: 4,
    imagen: "img/cleanjerk.jpg",
    titulo: 'Mejora tu RM de Clean & Jerk',
    profesor:'Matias Cambareri',
    calificacion: "img/45estrellas.png",
    precio: 3500,
    descuento:2800},

    {id: 5,
    imagen: "img/deadlift.webp",
    titulo: 'Fuerza en su Maxima expresio Deadlit',
    profesor:'Matias Cambareri',
    calificacion: "img/35estrellas.png",
    precio: 3500,
    descuento: 2600},

    {id: 6,
    imagen: "img/hsw.jpg",
    titulo: 'Aprende a caminar con las manos',
    profesor:'Matias Cambareri',
    calificacion: "img/4estrellas.png",
    precio: 2500,
    descuento: 2000},

    {id: 7,
    imagen: "img/pullups.jpg",
    titulo: 'Logra tu Primer Pull-up',
    profesor:'Matias Cambareri',
    calificacion: "img/5estrellas.png",
    precio: 2000,
    descuento: 1500},

    {id: 8,
    imagen: "img/ringmuscleups.webp",
    titulo: 'El Favorito Ring Muscle Ups',
    profesor:'Matias Cambareri',
    calificacion: "img/5estrellas.png",
    precio: 3500,
    descuento: 2800},

    {id: 9,
    imagen: "img/snatch.jpg",
    titulo: 'Mejora tu Rm de SNATCH',
    profesor:'Matias Cambareri',
    calificacion: "img/45estrellas.png",
    precio: 3500,
    descuento: 3000},

    {id: 10,
    imagen: "img/row.jpg",
    titulo: 'Acondicionamiento en Remo',
    profesor:'Matias Cambareri',
    calificacion: "img/4estrellas.png",
    precio: 2600,
    descuento: 2100},

    {id: 11,
    imagen: "img/toestobar.jpg",
    titulo: 'Consigue tus Toes to Bar',
    profesor:'Matias Cambareri',
    calificacion: "img/5estrellas.png",
    precio: 2000,
    descuento: 1500}

]